# Generated by Django 5.0.7 on 2025-01-11 10:37

from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('users', '0004_remove_customuser_role'),
#     ]

#     operations = [
#     ]


def add_employee_permission(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    CustomUser = apps.get_model('users', 'CustomUser')  # Replace with your app name

    content_type = ContentType.objects.get_for_model(CustomUser)
    Permission.objects.get_or_create(
        codename='is_employee',
        name='Employee Status',
        content_type=content_type,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_role'),  # Replace with your last migration name
    ]

    operations = [
        migrations.RunPython(add_employee_permission),
    ]