# Generated by Django 5.0.7 on 2025-05-05 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0010_businessapikey'),
        ('users', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('is_employee', 'Can act as an employee'), ('is_owner', 'Can act as a business owner')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Business.businessdetails'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
