# Generated by Django 5.0.7 on 2025-02-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesamessages',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mpesamessages',
            name='transaction_code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
