# Generated by Django 5.0.7 on 2025-03-06 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_alter_mpesamessages_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesamessages',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
