from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('customer/', views.customers, name='customers'),
    path('debtors/', views.debtors, name='debtors'),
    path('sales/', views.sales_func, name='sales'),
    path('locations/', views.location_func, name='location'),
    path('products/', views.product_func, name='product'),
    path('addcustomer/', views.add_customer, name='add-customer'),
    path('recordsales/', views.record_sales, name='record-sales'),
    path('recordOtherssales/', views.record_others_products_sales, name='record-sales'),
    path('employees/', views.all_employees, name='all-employees'),
    path('assignedcylider/', views.assignedProduct, name='assigned-cylinder'),
    path('assignedproduct/', views.assignedOtherProduct, name='assigned-product'),
    path('sendsms/', views.sendsms, name='send-sms'),
    path('sendbulksms/', views.sendbulksms, name='send-bulk-sms'),
    path('getsalesteam/', views.get_sales_team.as_view(), name='sales-team'),
    path('getsalesteam/<str:pk>/', views.get_sales_team.as_view(), name='sales-teamid'),
    path('addassignedcylinder/', views.assign_products, name = 'add_assigned_product'),
    path('sales-team-management/', views.sales_team_management, name='sales-team-management'),
    path('update_assigned_quantity/<str:pk>/', views.update_assigned_quantity, name='update_assigned_quantity'),
    path('createteam/', views.createteam),
    path('store/', views.Stores, name='store'),
    path('other-products/', views.OtherProductsViews.as_view(), name='store'),
    path('other-products/<str:pk>/', views.OtherProductsViews.as_view(), name='stores'),
    path('refill/', views.RefillOperations.as_view()),
    path('addnewcylinder/', views.AddNewCylinder.as_view()),
    path('updateCylinder/<str:pk>/', views.CylinderOperations.as_view()),
    path('updateThisCylinder/<str:pk>/<str:weightId>/', views.updateThiscylinder.as_view(), name='resolve_cylinder'),
    path('updateThisCylinder/<str:pk>/', views.updateThiscylinder.as_view(), name='resolve_cylinder'),
    path('addanothercylinder/<str:pk>/', views.AnotherCylinder.as_view()),
    path('assign-cylinders/', views.BulkAssignCylinderView.as_view(), name='assign-cylinders'),
    path('assign-update-cylinders/', views.BulkEditAssignCylinderView.as_view(), name='assign-cylinders'),
    path('the-assigned-cylinders/', views.AssignedCylindersListView.as_view(), name='assigned-cylinders-list'),
    path('print-assigned-cylinders/', views.AssignedCylindersPrintableView.as_view(), name='assigned-cylinders-list'),
    path('print-assigned-otherproduct/', views.OtherProductsRecietPrint.as_view(), name='assigned-product-list'),
    path('return-assigned-cylinders/', views.ReturnAssignedCylindersView.as_view(), name='return-assigned-cylinders'),
    path('return-all-assigned-cylinders/', views.ReturnAllAssignedCylindersView.as_view(), name='return-all-assigned-cylinders'),
    path('after-return/', views.ReturnCylindersPrintableView.as_view()),

    path('addspoiled/', views.addassignedProductSpoiled),
    path('updatespoiled/', views.updateassignedProductSpoiled),
    path('myprofile/', views.MyProfiles.as_view()),
    path('salesteamdata/', views.SalesRecordsView.as_view()),
    path('adminsalesteamdata/', views.AdminSalesRecordsView.as_view()),
    path('adminsverifyalesteamdata/<str:sale_id>/', views.AdminVerifySalesRecordsView.as_view()),
    path('check-user-status/', views.CheckUserStatusView.as_view()),
    path('transfer/<str:employee_id>/', views.transfer_employee),
    path('update-status/<str:employee_id>/', views.update_employee_status),
    path('clear_debt/<str:pk>/', views.DebtOperation.as_view()),
    path('mark-print-complete/', views.MarkPrintCompleteView.as_view(), name='mark-print-complete'),
    path('mark-print-complete-others/', views.MarkPrintOthersCompleteView.as_view(), name='mark-print-complete'),
    path('mark-print-return-complete/', views.MarkPrintReturnCompleteView.as_view(), name='mark-print-return-complete'),
    path('report-cylinder-losses/', views.AssingnedCylindersLost.as_view()),
    path('report-less_pay/', views.AssingnedCylindersLessPay.as_view()),
    path('defaults/<str:employee_id>/', views.DefaultedCylinders.as_view()),
    path('less-pay/<str:employee_id>/', views.DefaultedCylindersLessPay.as_view()),
    path('assign-others/', views.BulkAssignOtherProductsView.as_view()),
    path('cylinder-lost/<int:pk>/resolve/', views.resolve_cylinder_lost, name='resolve_cylinder_lost'),
    path('return-lost/<int:pk>/return/', views.return_cylinder_lost, name='return_cylinder_lost'),
    path('cylinder-less_pay/<int:pk>/resolve/', views.resolve_cylinder_lessPay, name='resolve_cylinder_lost'),
    path('expenses/<str:employee_id>/', views.ExpensesOperation.as_view()),
    path('update-owner-expense/<str:expense_id>/', views.ExpensesOwnerOperation.as_view(), name='owner-expenses'),
    path('team-expenses/<str:salesTeam_id>/', views.TeamExpensesOperation.as_view()),
    path('employees/<str:pk>/', views.single_employees, name='single-employees'),
    path('salary/<str:pk>/', views.EmployeeSalary.as_view(), name='salary-employees'),
    path('advances/<str:employeeId>/', views.AdvancesOperation.as_view()),
    path('clear-advances/<str:pk>/resolve/', views.resolve_advances.as_view(), name='resolve-advances'),
    path('cylinder-request/', views.CylinderRequest.as_view(), name='cylinder-request'),
    path('cylinder-request-get/<str:team_id>/', views.CylinderRequestGet.as_view(), name='cylinder-request-get'),
    path('cylinder-request-clear/<str:team_id>/', views.CylinderRequestClear.as_view(), name='cylinder-request-get'),
    path('all-request/', views.CylinderRequestedToMe.as_view()),
    path('approve-request/<str:cylinder_id>/', views.ApproveCylinderRequested.as_view()),
    path('cash/<str:employee_id>/', views.CashHandoutOperation.as_view()),
    path('cash/', views.CashHandoutOperation.as_view()),
    path('monthly-salary/<str:employee_id>/', views.MonthlySalaryOperation.as_view()),
    path('monthly-salary/', views.MonthlySalaryOperation.as_view()),
    path('search-customer/', views.SearchCustomer.as_view())
]