# Generated by Django 5.0.7 on 2025-05-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0091_remove_typeofsalesteam_business'),
        ('Business', '0023_businessdetails_is_trial_businessdetails_trial_end_and_more'),
        ('sales_ai', '0002_alter_prediction_customer_alter_purchase_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_quantity', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Business.businessdetails')),
                ('sales_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.salesteam')),
            ],
        ),
    ]
