# Generated by Django 5.0.7 on 2025-05-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_ai', '0003_salesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='sales_choice',
            field=models.CharField(blank=True, choices=[('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail')], max_length=20, null=True),
        ),
    ]
