# Generated by Django 5.0.7 on 2025-05-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0023_businessdetails_is_trial_businessdetails_trial_end_and_more'),
        ('sales_ai', '0006_refillcostanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Business.businessdetails')),
            ],
        ),
    ]
