# Generated by Django 5.0.7 on 2025-05-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_ai', '0007_companyexpenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyexpenses',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
