# Generated by Django 5.0.7 on 2025-05-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business_logo', models.ImageField(upload_to='logos')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
