# Generated by Django 5.0.7 on 2025-05-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0002_subscriptionoptions_businessname_subsription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionoptions',
            name='number_of_employees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionoptions',
            name='number_of_retail_shops',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionoptions',
            name='number_of_stores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionoptions',
            name='number_of_wholesale_shops',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
