# Generated by Django 5.0.7 on 2025-05-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0003_subscriptionoptions_number_of_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionoptions',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
