# Generated by Django 5.0.7 on 2025-05-05 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0004_subscriptionoptions_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionoptions',
            old_name='paid',
            new_name='highlight',
        ),
    ]
