# Generated by Django 5.0.7 on 2025-05-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0005_rename_paid_subscriptionoptions_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='subscriptionoptions',
            old_name='cost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='subscriptionoptions',
            name='date_subsribed',
        ),
        migrations.RemoveField(
            model_name='subscriptionoptions',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='subscriptionoptions',
            name='number_of_employees',
        ),
        migrations.RemoveField(
            model_name='subscriptionoptions',
            name='number_of_retail_shops',
        ),
        migrations.RemoveField(
            model_name='subscriptionoptions',
            name='number_of_stores',
        ),
        migrations.RemoveField(
            model_name='subscriptionoptions',
            name='number_of_wholesale_shops',
        ),
        migrations.AddField(
            model_name='subscriptionoptions',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
