# Generated by Django 5.0.7 on 2025-05-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0006_features_rename_cost_subscriptionoptions_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionoptions',
            name='features',
            field=models.ManyToManyField(to='Business.features'),
        ),
    ]
