# Generated by Django 5.0.7 on 2025-05-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0007_subscriptionoptions_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionoptions',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
