# Generated by Django 5.0.7 on 2025-05-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0008_alter_subscriptionoptions_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessName',
            new_name='BusinessDetails',
        ),
    ]
