# Generated by Django 5.0.7 on 2025-05-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0010_businessapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionoptions',
            name='employee_limit',
            field=models.IntegerField(default=5),
        ),
    ]
