# Generated by Django 5.0.7 on 2025-05-06 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0012_businessdetails_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdetails',
            old_name='Subsription_plan',
            new_name='subsription_plan',
        ),
    ]
