# Generated by Django 5.0.7 on 2025-05-06 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0013_rename_subsription_plan_businessdetails_subsription_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdetails',
            old_name='subsription_plan',
            new_name='subscription_plan',
        ),
    ]
