# Generated by Django 5.0.7 on 2025-05-06 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0014_rename_subsription_plan_businessdetails_subscription_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdetails',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
