# Generated by Django 5.0.7 on 2025-05-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0016_alter_businessdetails_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='subscription_plan_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
