# Generated by Django 5.0.7 on 2025-05-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0017_businessdetails_subscription_plan_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='subscription_period',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
