# Generated by Django 5.0.7 on 2025-05-08 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0019_subscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='subscription_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='subscription_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
