# Generated by Django 5.0.7 on 2025-05-08 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0020_subscriptionpayment_subscription_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='business',
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='subscription_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Business.subscriptionpayment'),
        ),
    ]
