# Generated by Django 5.0.7 on 2025-05-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0022_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
