# Generated by Django 5.0.7 on 2024-12-31 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wholesale_selling_price', models.PositiveIntegerField()),
                ('wholesale_refil_price', models.PositiveIntegerField()),
                ('retail_selling_price', models.PositiveIntegerField()),
                ('retail_refil_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CylinderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CylinderWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OtherProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('whole_sales_price', models.PositiveIntegerField(default=0)),
                ('retail_sales_price', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_of_operation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfSalesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.CharField(choices=[('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail')], max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('date_aded', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.locations')),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedCylinders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_quantity', models.PositiveIntegerField(default=0)),
                ('filled', models.PositiveIntegerField(default=0)),
                ('empties', models.PositiveIntegerField(default=0)),
                ('complete_sale', models.PositiveIntegerField(default=0)),
                ('refill_sale', models.PositiveIntegerField(default=0)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cylinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.cylinder')),
            ],
        ),
        migrations.CreateModel(
            name='CylinderStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled', models.PositiveIntegerField(default=0)),
                ('empties', models.PositiveIntegerField(default=0)),
                ('spoiled', models.PositiveIntegerField(default=0)),
                ('total_cylinders', models.PositiveIntegerField(default=0)),
                ('dates', models.DateTimeField()),
                ('date_of_operation', models.DateTimeField(auto_now_add=True)),
                ('cylinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.cylinder')),
            ],
        ),
        migrations.AddField(
            model_name='cylinder',
            name='gas_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.cylindertype'),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.cylinderweight'),
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('alternative_phone', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('front_id', models.ImageField(blank=True, null=True, upload_to='id_pictures')),
                ('back_id', models.ImageField(blank=True, null=True, upload_to='id_pictures')),
                ('verified', models.BooleanField(default=False)),
                ('defaulted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ManyToManyField(blank=True, to='BarakaApp.customers')),
                ('employees', models.ManyToManyField(blank=True, to='BarakaApp.employees')),
                ('location', models.ManyToManyField(blank=True, to='BarakaApp.locations')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('cleared', models.BooleanField(default=False)),
                ('cylinder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.cylinderstore')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.employees')),
                ('other_products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.otherproducts')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='sales_team_profile')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employees', models.ManyToManyField(blank=True, related_name='sales_teams', to='BarakaApp.employees')),
                ('type_of_sales_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.typeofsalesteam')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sales_type', models.CharField(choices=[('COMPLETESALE', 'completeSale'), ('REFILL', 'refillSale')], max_length=200, null=True)),
                ('sales_choice', models.CharField(blank=True, choices=[('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail')], max_length=200, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('partial_payment_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('debt_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('exchanged_with_local', models.BooleanField(default=False)),
                ('expected_date_to_repay', models.DateField(blank=True, null=True)),
                ('sales_person_payment_verified', models.BooleanField(default=False)),
                ('admin_payment_verified', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_sales', to='BarakaApp.customers')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.assignedcylinders')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.cylinderstore')),
                ('sales_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.salesteam')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='sales_team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='BarakaApp.salesteam'),
        ),
        migrations.CreateModel(
            name='Dbts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_given', models.DateField(auto_now_add=True)),
                ('expected_date_to_repay', models.DateField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_debt', to='BarakaApp.customers')),
                ('sales_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.salestab')),
                ('sales_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.salesteam')),
            ],
        ),
        migrations.AddField(
            model_name='assignedcylinders',
            name='sales_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesTeam', to='BarakaApp.salesteam'),
        ),
    ]
