# Generated by Django 5.0.7 on 2024-12-31 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcylinders',
            name='cylinder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.cylinderstore'),
        ),
    ]
