# Generated by Django 5.0.7 on 2024-12-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0002_alter_assignedcylinders_cylinder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='creator',
        ),
    ]
