# Generated by Django 5.0.7 on 2025-01-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0004_employees_fired_employees_suspended'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultedProducts',
        ),
    ]
