# Generated by Django 5.0.7 on 2025-01-02 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0005_delete_defaultedproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('cleared', models.BooleanField(default=False)),
                ('cylinder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.cylinderstore')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.employees')),
                ('other_products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.otherproducts')),
            ],
        ),
    ]
