# Generated by Django 5.0.7 on 2025-01-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0008_assignedcylinders_complete_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcylinders',
            name='refill_sale',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
