# Generated by Django 5.0.7 on 2025-01-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0009_assignedcylinders_refill_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcylinders',
            name='missing_cylinder',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
