# Generated by Django 5.0.7 on 2025-01-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0010_assignedcylinders_missing_cylinder'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcylinders',
            name='spoiled',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
