# Generated by Django 5.0.7 on 2025-01-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0011_assignedcylinders_spoiled'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='min_retail_refil_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='min_retail_selling_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='min_wholesale_refil_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='min_wholesale_selling_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
