# Generated by Django 5.0.7 on 2025-01-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0012_cylinder_min_retail_refil_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='max_retail_refil_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='max_retail_selling_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='max_wholesale_refil_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='max_wholesale_selling_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
