# Generated by Django 5.0.7 on 2025-01-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0013_cylinder_max_retail_refil_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
