# Generated by Django 5.0.7 on 2025-01-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0014_alter_employees_alternative_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestab',
            name='exchanged_with_local',
        ),
    ]
