# Generated by Django 5.0.7 on 2025-01-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0015_remove_salestab_exchanged_with_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestab',
            name='exchanged_with_local',
            field=models.BooleanField(default=False),
        ),
    ]
