# Generated by Django 5.0.7 on 2025-01-07 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0016_salestab_exchanged_with_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestab',
            name='date_sold',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 7, 23, 15, 19, 9869, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
