# Generated by Django 5.0.7 on 2025-01-09 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0017_salestab_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestab',
            name='sales_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.salesteam'),
        ),
    ]
