# Generated by Django 5.0.7 on 2025-01-10 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0018_alter_salestab_sales_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesteam',
            name='employees',
        ),
        migrations.AlterField(
            model_name='employees',
            name='sales_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='BarakaApp.salesteam'),
        ),
    ]
