# Generated by Django 5.0.7 on 2025-01-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0019_remove_salesteam_employees_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'permissions': [('employee_permission', 'Can act as an employee')]},
        ),
    ]
