# Generated by Django 5.0.7 on 2025-01-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0024_alter_dbts_creator_alter_dbts_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbts',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
