# Generated by Django 5.0.7 on 2025-01-29 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0025_dbts_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcylindersrecipt',
            name='assigned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignedcylindersrecipt',
            name='cylinder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.cylinderstore'),
        ),
        migrations.AddField(
            model_name='assignedcylindersrecipt',
            name='sales_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.salesteam'),
        ),
        migrations.CreateModel(
            name='ReturnClylindersReciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled', models.PositiveIntegerField(default=0)),
                ('empties', models.PositiveIntegerField(default=0)),
                ('spoiled', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cylinder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.cylinderstore')),
                ('sales_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.salesteam')),
            ],
        ),
    ]
