# Generated by Django 5.0.7 on 2025-01-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0026_assignedcylindersrecipt_assigned_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcylindersrecipt',
            name='print_complete',
            field=models.BooleanField(default=False),
        ),
    ]
