# Generated by Django 5.0.7 on 2025-01-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0027_assignedcylindersrecipt_print_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedcylindersrecipt',
            old_name='date',
            new_name='date_assigned',
        ),
    ]
