# Generated by Django 5.0.7 on 2025-01-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0028_rename_date_assignedcylindersrecipt_date_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnclylindersreciept',
            old_name='date',
            new_name='date_collected',
        ),
        migrations.AddField(
            model_name='returnclylindersreciept',
            name='print_complete',
            field=models.BooleanField(default=False),
        ),
    ]
