# Generated by Django 5.0.7 on 2025-02-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0029_rename_date_returnclylindersreciept_date_collected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcylinders',
            name='empties_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignedcylinders',
            name='filled_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='returnclylindersreciept',
            name='empties_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='returnclylindersreciept',
            name='filled_lost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
