# Generated by Django 5.0.7 on 2025-02-02 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0030_assignedcylinders_empties_lost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderLessPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_cylinder', models.PositiveIntegerField(default=0)),
                ('date_lost', models.DateTimeField(auto_now_add=True)),
                ('cylinder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.assignedcylinders')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.employees')),
            ],
        ),
        migrations.CreateModel(
            name='CylinderLost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_empty_cylinder', models.PositiveIntegerField(default=0)),
                ('number_of_filled_cylinder', models.PositiveIntegerField(default=0)),
                ('date_lost', models.DateTimeField(auto_now_add=True)),
                ('cylinder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.assignedcylinders')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.employees')),
            ],
        ),
    ]
