# Generated by Django 5.0.7 on 2025-02-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0031_cylinderlesspay_cylinderlost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cylinderlesspay',
            old_name='number_of_cylinder',
            new_name='cylinders_lost',
        ),
        migrations.AddField(
            model_name='assignedcylinders',
            name='less_pay',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='returnclylindersreciept',
            name='less_pay',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
