# Generated by Django 5.0.7 on 2025-02-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0033_rename_cylinders_lost_cylinderlesspay_cylinders_less_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinderlesspay',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cylinderlost',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
