# Generated by Django 5.0.7 on 2025-02-04 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0034_cylinderlesspay_resolved_cylinderlost_resolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedOtherProductRecipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_quantity', models.PositiveIntegerField(default=0)),
                ('print_complete', models.BooleanField(default=False)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.otherproducts')),
                ('sales_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.salesteam')),
            ],
        ),
    ]
