# Generated by Django 5.0.7 on 2025-03-11 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0036_otherproductsdbts_otherproductssalestab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salestab',
            old_name='admin_payment_verified',
            new_name='admin_cash_verified',
        ),
        migrations.AddField(
            model_name='cylinder',
            name='mid_retail_refil_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='mid_retail_selling_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='mid_wholesale_refil_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='mid_wholesale_selling_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salestab',
            name='admin_mpesa_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salestab',
            name='cash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salestab',
            name='mpesa_code',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_code', models.CharField(max_length=200)),
                ('second_mpesa_code', models.CharField(max_length=200)),
                ('third_mpesa_code', models.CharField(max_length=200)),
                ('cash', models.CharField(max_length=200)),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.salestab')),
            ],
        ),
    ]
