# Generated by Django 5.0.7 on 2025-03-12 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0037_rename_admin_payment_verified_salestab_admin_cash_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='salary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='total_defaults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.employees')),
            ],
        ),
    ]
