# Generated by Django 5.0.7 on 2025-03-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0038_employees_salary_employees_total_defaults_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
