# Generated by Django 5.0.7 on 2025-03-16 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0039_expenses_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinderlesspay',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
