# Generated by Django 5.0.7 on 2025-03-21 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0040_cylinderlesspay_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='salary',
            new_name='contract_salary',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='total_defaults',
        ),
        migrations.AddField(
            model_name='employees',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Advances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date_issued', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.employees')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField()),
                ('payment_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.employees')),
            ],
        ),
    ]
