# Generated by Django 5.0.7 on 2025-03-27 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0041_rename_salary_employees_contract_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advances',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
