# Generated by Django 5.0.7 on 2025-03-27 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0042_advances_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='advances',
            name='resolve',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UnaccountedFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.employees')),
            ],
        ),
    ]
