# Generated by Django 5.0.7 on 2025-03-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0043_advances_resolve_unaccountedfor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advances',
            old_name='resolve',
            new_name='resolved',
        ),
    ]
