# Generated by Django 5.0.7 on 2025-03-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0044_rename_resolve_advances_resolved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='checked',
            new_name='resolved',
        ),
    ]
