# Generated by Django 5.0.7 on 2025-03-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0045_rename_checked_expenses_resolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderRequestTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('given', models.BooleanField(default=True)),
                ('quantity_given', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cylinder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.assignedcylinders')),
                ('requesting_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.salesteam')),
            ],
        ),
    ]
