# Generated by Django 5.0.7 on 2025-03-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0047_cylinderrequesttransfer_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinderrequesttransfer',
            name='given',
            field=models.BooleanField(default=False),
        ),
    ]
