# Generated by Django 5.0.7 on 2025-03-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0048_alter_cylinderrequesttransfer_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
