# Generated by Django 5.0.7 on 2025-04-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0049_alter_employees_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcylinders',
            name='transfered_cylinder',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
