# Generated by Django 5.0.7 on 2025-04-03 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0050_assignedcylinders_transfered_cylinder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransaction',
            name='cash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_transaction', to='BarakaApp.salestab'),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='second_mpesa_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='third_mpesa_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
