# Generated by Django 5.0.7 on 2025-04-03 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0051_alter_salestransaction_cash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDeficit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.PositiveIntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
                ('deficit_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.employees')),
            ],
        ),
    ]
