# Generated by Django 5.0.7 on 2025-04-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0052_cashdeficit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salestab',
            old_name='cash',
            new_name='cashAmount',
        ),
    ]
