# Generated by Django 5.0.7 on 2025-04-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0053_rename_cash_salestab_cashamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestab',
            name='mpesaAmount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salestab',
            name='mpesaAmountOne',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
