# Generated by Django 5.0.7 on 2025-04-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0054_salestab_mpesaamount_salestab_mpesaamountone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestab',
            name='mpesaAmountOne',
        ),
    ]
