# Generated by Django 5.0.7 on 2025-04-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0056_alter_salestab_cashamount_alter_salestab_mpesaamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestab',
            name='cashAmount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salestab',
            name='mpesaAmount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
