# Generated by Django 5.0.7 on 2025-04-08 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0059_salestab_admin_payment_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='expense_on_choice',
            field=models.CharField(blank=True, choices=[('COMPANY', 'Company'), ('EMPLOYEE', 'Employee')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CashDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_at_hand', models.PositiveIntegerField(default=0)),
                ('amount_deficit', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.employees')),
            ],
        ),
        migrations.DeleteModel(
            name='UnaccountedFor',
        ),
    ]
