# Generated by Django 5.0.7 on 2025-04-08 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0060_expenses_expense_on_choice_cashdefault_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='sales_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BarakaApp.salesteam'),
        ),
    ]
