# Generated by Django 5.0.7 on 2025-04-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0062_alter_expenses_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashDeficit',
            new_name='CashHandOut',
        ),
    ]
