# Generated by Django 5.0.7 on 2025-04-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0063_rename_cashdeficit_cashhandout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashhandout',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
