# Generated by Django 5.0.7 on 2025-04-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0064_alter_cashhandout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashhandout',
            name='cash_default',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
