# Generated by Django 5.0.7 on 2025-04-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0066_cashhandout_sales_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashhandout',
            name='cash_default',
            field=models.IntegerField(default=0),
        ),
    ]
