# Generated by Django 5.0.7 on 2025-04-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0068_cylinder_empty_cylinder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestab',
            name='amount_sold_for',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
