# Generated by Django 5.0.7 on 2025-04-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0069_salestab_amount_sold_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestab',
            name='amount_sold_for_mpesa',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
