# Generated by Django 5.0.7 on 2025-04-25 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0070_salestab_amount_sold_for_mpesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedCylindersReciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(blank=True, max_length=200, null=True)),
                ('assigned_cylinders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.assignedcylinders')),
                ('sales_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.salesteam')),
            ],
        ),
    ]
