# Generated by Django 5.0.7 on 2025-04-26 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0071_assignedcylindersreciept'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestab',
            name='cylinder_exchanged_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_as_exchanged', to='BarakaApp.assignedcylinders'),
        ),
        migrations.AlterField(
            model_name='salestab',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_as_product', to='BarakaApp.assignedcylinders'),
        ),
    ]
