# Generated by Django 5.0.7 on 2025-04-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0072_salestab_cylinder_exchanged_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcylinders',
            name='cylinder_exchanged_with',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
