# Generated by Django 5.0.7 on 2025-04-26 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0073_assignedcylinders_cylinder_exchanged_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedcylinders',
            name='cylinder_exchanged_with',
        ),
    ]
