# Generated by Django 5.0.7 on 2025-04-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0074_remove_assignedcylinders_cylinder_exchanged_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
