# Generated by Django 5.0.7 on 2025-04-28 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0075_alter_customers_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylindersExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('exchanged_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanged_with', to='BarakaApp.assignedcylinders')),
                ('original_cylinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='BarakaApp.assignedcylinders')),
            ],
        ),
    ]
