# Generated by Django 5.0.7 on 2025-05-01 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0076_cylindersexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
