# Generated by Django 5.0.7 on 2025-05-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0077_monthlysalary_paid_on_alter_monthlysalary_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
