# Generated by Django 5.0.7 on 2025-05-05 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0078_alter_monthlysalary_payment_date'),
        ('Business', '0010_businessapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='advances',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedcylinders',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedcylindersreciept',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedcylindersrecipt',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedotherproductrecipt',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedotherproducts',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashdefault',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashhandout',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylinder',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylinderlesspay',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylinderlost',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylinderrequesttransfer',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylindersexchange',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylinderstore',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylindertype',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylinderweight',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbts',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultedproducts',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherproducts',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherproductsdbts',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherproductssalestab',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnclylindersreciept',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestab',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesteam',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeofsale',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeofsalesteam',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Business.businessdetails'),
            preserve_default=False,
        ),
    ]
