# Generated by Django 5.0.7 on 2025-05-16 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0080_alter_employees_first_name_alter_employees_gender_and_more'),
        ('Business', '0023_businessdetails_is_trial_businessdetails_trial_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='depot_refill_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CylindersRefilled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Business.businessdetails')),
                ('cylinder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarakaApp.cylinderstore')),
            ],
        ),
        migrations.CreateModel(
            name='CylinderDepotReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot_date', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Business.businessdetails')),
                ('cylinders_refilled', models.ManyToManyField(to='BarakaApp.cylindersrefilled')),
            ],
        ),
    ]
