# Generated by Django 5.0.7 on 2025-05-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0081_cylinder_depot_refill_price_cylindersrefilled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedcylinders',
            name='business',
        ),
        migrations.RemoveField(
            model_name='assignedotherproducts',
            name='business',
        ),
    ]
