# Generated by Django 5.0.7 on 2025-05-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0082_remove_assignedcylinders_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedcylindersreciept',
            name='business',
        ),
        migrations.RemoveField(
            model_name='assignedcylindersrecipt',
            name='business',
        ),
        migrations.RemoveField(
            model_name='assignedotherproductrecipt',
            name='business',
        ),
        migrations.RemoveField(
            model_name='cylinderlesspay',
            name='business',
        ),
        migrations.RemoveField(
            model_name='cylinderlost',
            name='business',
        ),
        migrations.RemoveField(
            model_name='cylindersexchange',
            name='business',
        ),
        migrations.RemoveField(
            model_name='returnclylindersreciept',
            name='business',
        ),
    ]
