# Generated by Django 5.0.7 on 2025-05-18 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0083_remove_assignedcylindersreciept_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
