# Generated by Django 5.0.7 on 2025-05-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0084_cylinder_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeportReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('date_of_refill', models.DateField()),
            ],
        ),
    ]
