# Generated by Django 5.0.7 on 2025-05-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0085_deportreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeportReport',
        ),
    ]
