# Generated by Django 5.0.7 on 2025-05-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0086_delete_deportreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherproducts',
            name='product_buying_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
