# Generated by Django 5.0.7 on 2025-05-20 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0088_otherproductspurchasereport'),
        ('Business', '0023_businessdetails_is_trial_businessdetails_trial_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestab',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Business.businessdetails'),
        ),
    ]
