# Generated by Django 5.0.7 on 2025-05-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0089_alter_salestab_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestransaction',
            name='business',
        ),
    ]
