# Generated by Django 5.0.7 on 2025-05-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakaApp', '0090_remove_salestransaction_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofsalesteam',
            name='business',
        ),
    ]
